language: node_js

os:
  - osx

node_js:
  - node

install:
  - npm install

cache:
  directories:
    - 'node_modules'

script:
  - npm run lint
  - npm test
  - npm run vscode:prepublish

notifications:
  email: false
